"""Export strategies to Pine Script for TradingView's Strategy Tester.

Why bother, when we already have a backtester? **Because two independent
implementations disagreeing is the cheapest bug detector available.** If this
engine says +37% and TradingView says +340% on the same rule and the same
bars, one of them is wrong, and finding out which teaches you more than either
number alone. Agreement is weak evidence both are right; disagreement is
strong evidence one is broken.

In practice the disagreement is usually TradingView's, and usually for one of
the reasons listed in :data:`TESTER_TRAPS` - which is why the generated script
sets the defensive options explicitly rather than relying on defaults.

The generated scripts pin four things that the Strategy Tester gets wrong or
silently omits by default:

* ``process_orders_on_close=false`` - orders fill on the NEXT bar's open, the
  same anti-look-ahead rule this engine enforces. The default fills on the
  close of the bar that generated the signal, which is a price you could not
  have traded at.
* ``commission_value`` and ``slippage`` are set from the chosen cost preset.
  The tester defaults both to **zero**, which is how a losing strategy becomes
  a winning one on screen.
* ``calc_on_every_tick=false`` - so results are reproducible rather than
  depending on when you happened to load the chart.
* ``default_qty_type=strategy.percent_of_equity`` - matching how this engine
  sizes positions, so the two are comparable at all.
"""

from __future__ import annotations

from .costs import CostModel
from .strategy.base import Strategy
from .strategy.library import (
    BuyAndHold, MeanReversion, Momentum, PriceVsSma, SmaCrossover,
)

TESTER_TRAPS = [
    "Non-standard chart types (Heikin Ashi, Renko, Kagi, Point & Figure) "
    "produce fantasy fills - the tester trades the synthetic candle's price, "
    "which never existed. Always backtest on a standard candlestick chart.",

    "Commission and slippage default to ZERO in the Strategy Tester "
    "properties. A strategy trading weekly can look profitable purely "
    "because nobody filled those two boxes in.",

    "`request.security()` without `lookahead=barmerge.lookahead_off` returns "
    "higher-timeframe data before it closed. This is the classic multi-"
    "timeframe look-ahead bug and it produces spectacular, impossible equity "
    "curves.",

    "Repainting indicators (anything recalculating historical values as new "
    "bars arrive) backtest perfectly and fail live. If the signal moves when "
    "you reload the chart, it repaints.",

    "`process_orders_on_close=true` fills at the close of the bar that "
    "generated the signal - information you did not have when the signal "
    "fired.",

    "Bar limits vary by plan tier, so your 'ten year' backtest may silently "
    "cover far less. Check the number of bars actually tested.",

    "A single asset over a single period is one sample. An asset chosen "
    "because it went up a lot (Bitcoin since 2015) flatters any long-biased "
    "trend rule - that is selection bias, not an edge.",
]


def _header(strategy: Strategy, costs: CostModel, *, initial_capital: float) -> str:
    commission_pct = round(costs.commission_pct * 100, 4)
    # Half-spread per side plus slippage, expressed in ticks-as-percent.
    slippage_pct = round((costs.spread_pct / 2 + costs.slippage_pct) * 100, 4)
    return f'''//@version=5
// Generated by brokerbot from {strategy.describe()}
//
// Cross-check this against `python -m brokerbot.cli backtest`. If the two
// disagree materially on the same symbol and period, one is wrong - see
// `python -m brokerbot.cli pine --traps` for the usual culprits.
strategy("brokerbot: {strategy.describe()}",
     overlay=true,
     initial_capital={initial_capital:.0f},
     default_qty_type=strategy.percent_of_equity,
     default_qty_value=100,
     commission_type=strategy.commission.percent,
     commission_value={commission_pct},
     slippage={max(1, int(slippage_pct * 100))},
     // Fill on the NEXT bar's open, never the signal bar's close.
     process_orders_on_close=false,
     calc_on_every_tick=false,
     calc_on_order_fills=false,
     pyramiding=0)

// Slippage above is in ticks; verify it against this symbol's tick size in
// the Strategy Tester properties. Commission is {commission_pct}% per side.
'''


def _body(strategy: Strategy) -> str:
    if isinstance(strategy, PriceVsSma):
        return f'''
length = input.int({strategy.window}, "SMA length")
sma = ta.sma(close, length)
plot(sma, "SMA", color=color.purple, linewidth=2)

longCondition = close > sma
if longCondition and strategy.position_size == 0
    strategy.entry("Long", strategy.long)
if not longCondition and strategy.position_size > 0
    strategy.close("Long")
'''
    if isinstance(strategy, SmaCrossover):
        return f'''
fastLen = input.int({strategy.fast}, "Fast SMA")
slowLen = input.int({strategy.slow}, "Slow SMA")
fast = ta.sma(close, fastLen)
slow = ta.sma(close, slowLen)
plot(fast, "Fast", color=color.blue)
plot(slow, "Slow", color=color.orange)

if ta.crossover(fast, slow)
    strategy.entry("Long", strategy.long)
if ta.crossunder(fast, slow)
    strategy.close("Long")
'''
    if isinstance(strategy, Momentum):
        return f'''
lookback = input.int({strategy.lookback}, "Lookback bars")
threshold = input.float({strategy.threshold}, "Return threshold")
trailing = close / close[lookback] - 1
plot(trailing, "Trailing return", display=display.data_window)

if trailing > threshold and strategy.position_size == 0
    strategy.entry("Long", strategy.long)
if trailing <= threshold and strategy.position_size > 0
    strategy.close("Long")
'''
    if isinstance(strategy, MeanReversion):
        return f'''
win = input.int({strategy.window}, "Window")
entryZ = input.float({strategy.entry_z}, "Entry z-score")
exitZ = input.float({strategy.exit_z}, "Exit z-score")
basis = ta.sma(close, win)
dev = ta.stdev(close, win)
z = dev > 0 ? (close - basis) / dev : 0.0
plot(basis, "Basis", color=color.gray)

if z <= entryZ and strategy.position_size == 0
    strategy.entry("Long", strategy.long)
if z >= exitZ and strategy.position_size > 0
    strategy.close("Long")
'''
    if isinstance(strategy, BuyAndHold):
        return '''
// The benchmark every strategy must beat. Enter once, never exit.
if strategy.position_size == 0
    strategy.entry("Long", strategy.long)
'''
    raise ValueError(
        f"no Pine template for {type(strategy).__name__}. Strategies driven by "
        f"external data (news, order flow) cannot be expressed in Pine Script - "
        f"it only sees the chart."
    )


def export(strategy: Strategy, costs: CostModel, *,
           initial_capital: float = 100_000.0) -> str:
    """Render a strategy as a self-contained Pine v5 script."""
    return _header(strategy, costs, initial_capital=initial_capital) + _body(strategy)


def traps_text() -> str:
    lines = ["TradingView Strategy Tester: what inflates results", ""]
    for i, trap in enumerate(TESTER_TRAPS, 1):
        lines.append(f"{i}. {trap}")
        lines.append("")
    lines.append(
        "A backtest is a measurement. Every one of the above makes the "
        "measurement flatter the strategy, and none of them announce "
        "themselves - the equity curve just looks better."
    )
    return "\n".join(lines)
